name: Deploy Notes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        # -U लगाकर हम लेटेस्ट लाइब्रेरीज़ इंस्टॉल कर रहे हैं ताकि एरर न आए
        run: pip install -U google-generativeai requests
        
      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MY_PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
          GITHUB_USERNAME: "jatin-9096"
          GITHUB_REPO: "Shorveer_notes"
        run: python main.py
        
